<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageId>KOtp.Kiota.Poc</PackageId>
    <Version>0.0.0-poc</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="generated/**/*.cs" />
    <PackageReference Include="Microsoft.Kiota.Bundle" Version="2.0.0" />
  </ItemGroup>
</Project>
